### ISSUE TITLE
Race condition in loader.go

### ISSUE THREAD

**Issue by rafaelgieschke** [lucaslorentz/caddy-docker-proxy#306]
Very infrequently, caddy-docker-proxy crashes Caddy directly at start, producing this stack trace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4967f4]

goroutine 54 [running]:
time.(*Timer).Reset(0x0, 0xc000065724)
     time/sleep.go:135 +0x14
github.com/lucaslorentz/caddy-docker-proxy/plugin/v2.(*DockerLoader).update(0xc0002a4480)
     github.com/lucaslorentz/caddy-docker-proxy/plugin/v2@v2.0.0-20210921063940-e98eb319a732/loader.go:161 +0x45
github.com/lucaslorentz/caddy-docker-proxy/plugin/v2.(*DockerLoader).Start.func1()
     github.com/lucaslorentz/caddy-docker-proxy/plugin/v2@v2.0.0-20210921063940-e98eb319a732/loader.go:94 +0x1d
created by time.goFunc
     time/sleep.go:180 +0x31
```

I think this is due to a race condition in <https://github.com/lucaslorentz/caddy-docker-proxy/blob/8cdb12bfb899241c801fc2003306c7b87e1be5fb/plugin/loader.go#L93-L95>, where the function can be called before `dockerLoader.timer =` has finished and `dockerLoader.timer` is still `nil` at <https://github.com/lucaslorentz/caddy-docker-proxy/blob/8cdb12bfb899241c801fc2003306c7b87e1be5fb/plugin/loader.go#L161>.

Probably something (untested) along the lines of:

```patch
+		ready := make(chan struct{})
 		dockerLoader.timer = time.AfterFunc(0, func() {
+			<-ready
 			dockerLoader.update()
 		})
+		close(ready)
```

would help.

**Comment by lucaslorentz** [comment]
Very nice finding!
I agree with the suggested code change, feel free to create a Pull Request.
Or I will create one later.
