### ISSUE TITLE
Unable to build custom container with  CADDY_VERSION=2.6.3

### ISSUE THREAD

**Issue by samcro1967** [lucaslorentz/caddy-docker-proxy#458]
Getting an error when trying to build a new container with the latest version of Caddy.  If I comment out `--with github.com/lucaslorentz/caddy-docker-proxy/v2 \`, the container builds as expected.

2.6.2 builds without issue.  Dockerfile and build logs are below.

<details>
  <summary>Dockerfile</summary>

```
ARG CADDY_VERSION=2.6.3

FROM caddy:${CADDY_VERSION}-builder AS builder
#FROM caddy:builder AS builder

RUN xcaddy build \
    --with github.com/lucaslorentz/caddy-docker-proxy/v2 \
    --with github.com/greenpau/caddy-security \
    --with github.com/crewjam/saml@v0.4.10=github.com/greenpau/origin_crewjam_saml@v0.4.11-0.20221229165346-936eba92623a \
    --with github.com/greenpau/caddy-trace \
    --with github.com/porech/caddy-maxmind-geolocation \
    --with github.com/caddy-dns/cloudflare \
    --with github.com/kirsch33/realip

FROM caddy:${CADDY_VERSION}-alpine
#FROM caddy:builder-alpine

RUN apk add --no-cache tzdata

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

CMD ["caddy", "docker-proxy"]
```
</details>

<details>
  <summary>Logs</summary>

```
latest: Pulling from plugins/docker
Digest: sha256:ea4e85abad2717e19427610186315f4a4628d5100ac3040e73febdb54442c497
Status: Image is up to date for plugins/docker:latest
+ /usr/local/bin/dockerd --data-root /var/lib/docker --host=unix:///var/run/docker.sock --insecure-registry ******
Registry credentials or Docker config not provided. Guest mode enabled.
+ /usr/local/bin/docker version
Client:
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:45:09 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:49:54 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
+ /usr/local/bin/docker info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-1031-azure
 Operating System: Alpine Linux v3.15
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.12GiB
 Name: ffd91f2ef460
 ID: XBSQ:LJ27:JSIG:Y4KD:KWYU:5NCP:GTYE:DOHD:I657:HY34:Q7AD:IS3Z
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  ******
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

+ /usr/local/bin/docker build --rm=true -f /drone/src/Dockerfile -t e6e9b988a1d152508209efee8b12f56bf832d290 . --pull=true --label org.opencontainers.image.created=2023-02-09T10:58:07Z --label org.opencontainers.image.revision=e6e9b988a1d152508209efee8b12f56bf832d290 --label org.opencontainers.image.source=http://osu.gitea:3069/osuhickeys/caddy.git --label org.opencontainers.image.url=http://osu.gitea:3069/osuhickeys/caddy
Sending build context to Docker daemon  96.26kB

Step 1/11 : ARG CADDY_VERSION=2.6.3
Step 2/11 : FROM caddy:${CADDY_VERSION}-builder AS builder
2.6.3-builder: Pulling from library/caddy
8921db27df28: Pulling fs layer
a2f8637abd91: Pulling fs layer
d48e7ca896ec: Pulling fs layer
4f26d270037d: Pulling fs layer
807cf12e90d6: Pulling fs layer
ca1e21e61982: Pulling fs layer
a86c409f0ecb: Pulling fs layer
807cf12e90d6: Waiting
ca1e21e61982: Waiting
a86c409f0ecb: Waiting
4f26d270037d: Waiting
a2f8637abd91: Verifying Checksum
a2f8637abd91: Download complete
8921db27df28: Verifying Checksum
8921db27df28: Download complete
8921db27df28: Pull complete
a2f8637abd91: Pull complete
807cf12e90d6: Verifying Checksum
807cf12e90d6: Download complete
4f26d270037d: Download complete
ca1e21e61982: Verifying Checksum
ca1e21e61982: Download complete
d48e7ca896ec: Verifying Checksum
d48e7ca896ec: Download complete
a86c409f0ecb: Verifying Checksum
a86c409f0ecb: Download complete
d48e7ca896ec: Pull complete
4f26d270037d: Pull complete
807cf12e90d6: Pull complete
ca1e21e61982: Pull complete
a86c409f0ecb: Pull complete
Digest: sha256:458901eb7e2d1f60ea430e23833e47d4b3ada93d601df57a34674b67675483b1
Status: Downloaded newer image for caddy:2.6.3-builder
 ---> 858147920561
Step 3/11 : RUN xcaddy build     --with github.com/greenpau/caddy-security     --with github.com/crewjam/saml@v0.4.10=github.com/greenpau/origin_crewjam_saml@v0.4.11-0.20221229165346-936eba92623a     --with github.com/greenpau/caddy-trace     --with github.com/porech/caddy-maxmind-geolocation     --with github.com/caddy-dns/cloudflare     --with github.com/kirsch33/realip
 ---> Running in 97d186569d4c
2023/02/09 10:58:16 [INFO] Temporary folder: /tmp/buildenv_2023-02-09-1058.4285785816
2023/02/09 10:58:16 [INFO] Writing main module: /tmp/buildenv_2023-02-09-1058.4285785816/main.go
package main

import (
	caddycmd "github.com/caddyserver/caddy/v2/cmd"

	// plug in Caddy modules here
	_ "github.com/caddyserver/caddy/v2/modules/standard"
	_ "github.com/greenpau/caddy-security"
	_ "github.com/crewjam/saml"
	_ "github.com/greenpau/caddy-trace"
	_ "github.com/porech/caddy-maxmind-geolocation"
	_ "github.com/caddy-dns/cloudflare"
	_ "github.com/kirsch33/realip"
)

func main() {
	caddycmd.Main()
}
2023/02/09 10:58:16 [INFO] Initializing Go module
2023/02/09 10:58:16 [INFO] exec (timeout=10s): /usr/local/go/bin/go mod init caddy 
go: creating new go.mod: module caddy
go: to add module requirements and sums:
	go mod tidy
2023/02/09 10:58:16 [INFO] Replace github.com/crewjam/saml => github.com/greenpau/origin_crewjam_saml@v0.4.11-0.20221229165346-936eba92623a
2023/02/09 10:58:16 [INFO] exec (timeout=10s): /usr/local/go/bin/go mod edit -replace github.com/crewjam/saml=github.com/greenpau/origin_crewjam_saml@v0.4.11-0.20221229165346-936eba92623a 
2023/02/09 10:58:16 [INFO] Pinning versions
2023/02/09 10:58:16 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/caddyserver/caddy/v2@v2.6.3 
go: downloading github.com/caddyserver/caddy/v2 v2.6.3
go: downloading github.com/caddyserver/certmagic v0.17.2
go: downloading github.com/prometheus/client_golang v1.14.0
go: downloading github.com/google/uuid v1.3.0
go: downloading github.com/quic-go/quic-go v0.32.0
go: downloading go.uber.org/zap v1.24.0
go: downloading golang.org/x/sys v0.5.0
go: downloading golang.org/x/term v0.5.0
go: downloading github.com/klauspost/cpuid/v2 v2.2.3
go: downloading github.com/libdns/libdns v0.2.1
go: downloading github.com/mholt/acmez v1.0.4
go: downloading github.com/miekg/dns v1.1.50
go: downloading golang.org/x/crypto v0.5.0
go: downloading golang.org/x/net v0.5.0
go: downloading go.uber.org/atomic v1.9.0
go: downloading go.uber.org/multierr v1.6.0
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/cespare/xxhash/v2 v2.1.2
go: downloading github.com/golang/protobuf v1.5.2
go: downloading github.com/prometheus/client_model v0.3.0
go: downloading github.com/prometheus/common v0.37.0
go: downloading github.com/cespare/xxhash v1.1.0
go: downloading github.com/prometheus/procfs v0.8.0
go: downloading google.golang.org/protobuf v1.28.1
go: downloading github.com/golang/mock v1.6.0
go: downloading github.com/onsi/ginkgo/v2 v2.2.0
go: downloading github.com/quic-go/qpack v0.4.0
go: downloading golang.org/x/tools v0.2.0
go: downloading golang.org/x/exp v0.0.0-20221205204356-47842c84f3db
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/quic-go/qtls-go1-18 v0.2.0
go: downloading github.com/quic-go/qtls-go1-19 v0.2.0
go: downloading github.com/quic-go/qtls-go1-20 v0.1.0
go: downloading golang.org/x/text v0.6.0
go: downloading golang.org/x/mod v0.6.0
go: downloading github.com/go-task/slim-sprig v0.0.0-20210107165309-348f09dbbbc0
go: downloading github.com/google/pprof v0.0.0-20210407192527-94a9f03dee38
go: added github.com/beorn7/perks v1.0.1
go: added github.com/caddyserver/caddy/v2 v2.6.3
go: added github.com/caddyserver/certmagic v0.17.2
go: added github.com/cespare/xxhash/v2 v2.1.2
go: added github.com/go-task/slim-sprig v0.0.0-20210107165309-348f09dbbbc0
go: added github.com/golang/mock v1.6.0
go: added github.com/golang/protobuf v1.5.2
go: added github.com/google/pprof v0.0.0-20210407192527-94a9f03dee38
go: added github.com/google/uuid v1.3.0
go: added github.com/klauspost/cpuid/v2 v2.2.3
go: added github.com/libdns/libdns v0.2.1
go: added github.com/matttproud/golang_protobuf_extensions v1.0.1
go: added github.com/mholt/acmez v1.0.4
go: added github.com/miekg/dns v1.1.50
go: added github.com/onsi/ginkgo/v2 v2.2.0
go: added github.com/prometheus/client_golang v1.14.0
go: added github.com/prometheus/client_model v0.3.0
go: added github.com/prometheus/common v0.37.0
go: added github.com/prometheus/procfs v0.8.0
go: added github.com/quic-go/qpack v0.4.0
go: added github.com/quic-go/qtls-go1-18 v0.2.0
go: added github.com/quic-go/qtls-go1-19 v0.2.0
go: added github.com/quic-go/qtls-go1-20 v0.1.0
go: added github.com/quic-go/quic-go v0.32.0
go: added go.uber.org/atomic v1.9.0
go: added go.uber.org/multierr v1.6.0
go: added go.uber.org/zap v1.24.0
go: added golang.org/x/crypto v0.5.0
go: added golang.org/x/exp v0.0.0-20221205204356-47842c84f3db
go: added golang.org/x/mod v0.6.0
go: added golang.org/x/net v0.5.0
go: added golang.org/x/sys v0.5.0
go: added golang.org/x/term v0.5.0
go: added golang.org/x/text v0.6.0
go: added golang.org/x/tools v0.2.0
go: added google.golang.org/protobuf v1.28.1
2023/02/09 10:58:23 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/greenpau/caddy-security github.com/caddyserver/caddy/v2@v2.6.3 
go: downloading github.com/greenpau/caddy-security v1.1.18
go: downloading github.com/greenpau/go-authcrunch v1.0.39
go: downloading go.uber.org/atomic v1.10.0
go: downloading go.uber.org/multierr v1.9.0
go: downloading github.com/dustin/go-humanize v1.0.1
go: downloading golang.org/x/sync v0.1.0
go: downloading github.com/google/cel-go v0.13.0
go: downloading google.golang.org/genproto v0.0.0-20230202175211-008b39050e57
go: downloading github.com/emersion/go-sasl v0.0.0-20220912192320-0145f2c60ead
go: downloading github.com/skip2/go-qrcode v0.0.0-20200617195104-da1b6568686e
go: downloading github.com/emersion/go-smtp v0.15.0
go: downloading github.com/smallstep/certificates v0.23.2
go: downloading github.com/smallstep/truststore v0.12.1
go: downloading go.step.sm/crypto v0.23.2
go: downloading github.com/tailscale/tscert v0.0.0-20230124224810-c6dc1f4049b2
go: downloading github.com/aryann/difflib v0.0.0-20210328193216-ff5ff6dc229b
go: downloading github.com/spf13/cobra v1.6.1
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/antlr/antlr4/runtime/Go/antlr v1.4.10
go: downloading github.com/stoewer/go-strcase v1.2.0
go: downloading github.com/greenpau/versioned v1.0.27
go: downloading github.com/golang-jwt/jwt/v4 v4.4.3
go: downloading howett.net/plist v1.0.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/smallstep/nosql v0.5.0
go: downloading go.step.sm/cli-utils v0.7.5
go: downloading go.step.sm/linkedca v0.19.0
go: downloading google.golang.org/grpc v1.52.3
go: downloading gopkg.in/square/go-jose.v2 v2.6.0
go: downloading github.com/greenpau/origin_crewjam_saml v0.4.11-0.20221229165346-936eba92623a
go: downloading github.com/go-ldap/ldap/v3 v3.4.4
go: downloading github.com/slackhq/nebula v1.6.1
go: downloading github.com/inconshreveable/mousetrap v1.0.1
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.2
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading filippo.io/edwards25519 v1.0.0
go: downloading github.com/Masterminds/sprig/v3 v3.2.3
go: downloading github.com/Microsoft/go-winio v0.6.0
go: downloading github.com/mitchellh/go-ps v1.0.0
go: downloading github.com/micromdm/scep/v2 v2.1.0
go: downloading go.mozilla.org/pkcs7 v0.0.0-20210826202110-33d05740a352
go: downloading github.com/urfave/cli v1.22.12
go: downloading github.com/chzyer/readline v0.0.0-20180603132655-2972be24d48e
go: downloading github.com/manifoldco/promptui v0.9.0
go: downloading github.com/Azure/go-ntlmssp v0.0.0-20221128193559-754e69321358
go: downloading github.com/go-asn1-ber/asn1-ber v1.5.4
go: downloading github.com/beevik/etree v1.1.0
go: downloading github.com/mattermost/xml-roundtrip-validator v0.1.0
go: downloading github.com/russellhaering/goxmldsig v1.2.0
go: downloading github.com/crewjam/httperr v0.2.0
go: downloading github.com/dgraph-io/badger v1.6.2
go: downloading github.com/russross/blackfriday/v2 v2.1.0
go: downloading github.com/dgraph-io/badger/v2 v2.2007.4
go: downloading go.etcd.io/bbolt v1.3.6
go: downloading github.com/go-sql-driver/mysql v1.6.0
go: downloading github.com/jackc/pgx/v4 v4.17.2
go: downloading github.com/Masterminds/goutils v1.1.1
go: downloading github.com/Masterminds/semver/v3 v3.2.0
go: downloading github.com/huandu/xstrings v1.3.3
go: downloading github.com/imdario/mergo v0.3.12
go: downloading github.com/mitchellh/copystructure v1.2.0
go: downloading github.com/shopspring/decimal v1.2.0
go: downloading github.com/spf13/cast v1.4.1
go: downloading github.com/go-kit/kit v0.10.0
go: downloading github.com/jonboulle/clockwork v0.3.0
go: downloading github.com/dgraph-io/ristretto v0.1.0
go: downloading github.com/dgryski/go-farm v0.0.0-20200201041132-a6ae2369ad13
go: downloading github.com/jackc/pgconn v1.13.0
go: downloading github.com/jackc/pgio v1.0.0
go: downloading github.com/jackc/pgproto3/v2 v2.3.1
go: downloading github.com/jackc/pgtype v1.12.0
go: downloading github.com/mgutz/ansi v0.0.0-20200706080929-d51e80ef957d
go: downloading github.com/AndreasBriese/bbloom v0.0.0-20190825152654-46b345b51c96
go: downloading github.com/mitchellh/reflectwalk v1.0.2
go: downloading github.com/golang/snappy v0.0.4
go: downloading github.com/klauspost/compress v1.15.15
go: downloading github.com/jackc/chunkreader/v2 v2.0.1
go: downloading github.com/jackc/pgpassfile v1.0.0
go: downloading github.com/jackc/pgservicefile v0.0.0-20200714003250-2b9c44734f2b
go: downloading github.com/golang/glog v1.0.0
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
go: downloading github.com/go-logfmt/logfmt v0.5.1
go: downloading github.com/mattn/go-colorable v0.1.8
go: downloading github.com/mattn/go-isatty v0.0.13
go: added github.com/Azure/go-ntlmssp v0.0.0-20221128193559-754e69321358
go: added github.com/beevik/etree v1.1.0
go: added github.com/crewjam/httperr v0.2.0
go: added github.com/crewjam/saml v0.4.11-0.20230112210550-cfc9c7538d2c
go: added github.com/emersion/go-sasl v0.0.0-20220912192320-0145f2c60ead
go: added github.com/emersion/go-smtp v0.15.0
go: added github.com/go-asn1-ber/asn1-ber v1.5.4
go: added github.com/go-ldap/ldap/v3 v3.4.4
go: added github.com/golang-jwt/jwt/v4 v4.4.3
go: added github.com/greenpau/caddy-security v1.1.18
go: added github.com/greenpau/go-authcrunch v1.0.39
go: added github.com/greenpau/versioned v1.0.27
go: added github.com/jonboulle/clockwork v0.3.0
go: added github.com/mattermost/xml-roundtrip-validator v0.1.0
go: added github.com/russellhaering/goxmldsig v1.2.0
go: added github.com/skip2/go-qrcode v0.0.0-20200617195104-da1b6568686e
go: upgraded go.uber.org/atomic v1.9.0 => v1.10.0
go: upgraded go.uber.org/multierr v1.6.0 => v1.9.0
2023/02/09 10:58:36 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/greenpau/caddy-trace github.com/caddyserver/caddy/v2@v2.6.3 
go: downloading github.com/greenpau/caddy-trace v1.1.10
panic: internal error: can't find reason for requirement on github.com/google/pprof@v0.0.0-20210407192527-94a9f03dee38

goroutine 1 [running]:
cmd/go/internal/modget.(*resolver).updateBuildList.func1({{0xc0004cd818?, 0xc0002d65b8?}, {0xc00011e840?, 0xc0004da518?}})
	/usr/local/go/src/cmd/go/internal/modget/get.go:1760 +0x114
cmd/go/internal/modget.(*resolver).updateBuildList(0xc0000d8600, {0xb2e7b0, 0xc00002a058}, {0x0, 0x0, 0x0})
	/usr/local/go/src/cmd/go/internal/modget/get.go:1765 +0x597
cmd/go/internal/modget.(*resolver).resolveQueries(0xc0000d8600, {0xb2e7b0, 0xc00002a058}, {0xc0000675f0, 0x2, 0x472485?})
	/usr/local/go/src/cmd/go/internal/modget/get.go:1243 +0x1e5
cmd/go/internal/modget.runGet({0xb2e7b0, 0xc00002a058}, 0xc000028498?, {0xc000024220, 0x2, 0x2})
	/usr/local/go/src/cmd/go/internal/modget/get.go:314 +0x40b
main.invoke(0xe28fa0, {0xc0000241f0, 0x5, 0x5})
	/usr/local/go/src/cmd/go/main.go:225 +0x34e
main.main()
	/usr/local/go/src/cmd/go/main.go:179 +0x7d1
2023/02/09 10:58:38 [FATAL] exit status 2
The command '/bin/sh -c xcaddy build     --with github.com/greenpau/caddy-security     --with github.com/crewjam/saml@v0.4.10=github.com/greenpau/origin_crewjam_saml@v0.4.11-0.20221229165346-936eba92623a     --with github.com/greenpau/caddy-trace     --with github.com/porech/caddy-maxmind-geolocation     --with github.com/caddy-dns/cloudflare     --with github.com/kirsch33/realip' returned a non-zero code: 1
exit status 1
panic: internal error: can't find reason for requirement on github.com/google/pprof@v0.0.0-20210407192527-94a9f03dee38

goroutine 1 [running]:
cmd/go/internal/modget.(*resolver).updateBuildList.func1({{0xc0004cd818?, 0xc0002d65b8?}, {0xc00011e840?, 0xc0004da518?}})
	/usr/local/go/src/cmd/go/internal/modget/get.go:1760 +0x114
cmd/go/internal/modget.(*resolver).updateBuildList(0xc0000d8600, {0xb2e7b0, 0xc00002a058}, {0x0, 0x0, 0x0})
	/usr/local/go/src/cmd/go/internal/modget/get.go:1765 +0x597
cmd/go/internal/modget.(*resolver).resolveQueries(0xc0000d8600, {0xb2e7b0, 0xc00002a058}, {0xc0000675f0, 0x2, 0x472485?})
	/usr/local/go/src/cmd/go/internal/modget/get.go:1243 +0x1e5
cmd/go/internal/modget.runGet({0xb2e7b0, 0xc00002a058}, 0xc000028498?, {0xc000024220, 0x2, 0x2})
	/usr/local/go/src/cmd/go/internal/modget/get.go:314 +0x40b
main.invoke(0xe28fa0, {0xc0000241f0, 0x5, 0x5})
	/usr/local/go/src/cmd/go/main.go:225 +0x34e
main.main()
	/usr/local/go/src/cmd/go/main.go:179 +0x7d1
2023/02/09 10:58:38 [FATAL] exit status 2
The command '/bin/sh -c xcaddy build     --with github.com/greenpau/caddy-security     --with github.com/crewjam/saml@v0.4.10=github.com/greenpau/origin_crewjam_saml@v0.4.11-0.20221229165346-936eba92623a     --with github.com/greenpau/caddy-trace     --with github.com/porech/caddy-maxmind-geolocation     --with github.com/caddy-dns/cloudflare     --with github.com/kirsch33/realip' returned a non-zero code: 1
exit status 1
panic: internal error: can't find reason for requirement on github.com/google/pprof@v0.0.0-20210407192527-94a9f03dee38

goroutine 1 [running]:
cmd/go/internal/modget.(*resolver).updateBuildList.func1({{0xc0004cd818?, 0xc0002d65b8?}, {0xc00011e840?, 0xc0004da518?}})
	/usr/local/go/src/cmd/go/internal/modget/get.go:1760 +0x114
cmd/go/internal/modget.(*resolver).updateBuildList(0xc0000d8600, {0xb2e7b0, 0xc00002a058}, {0x0, 0x0, 0x0})
	/usr/local/go/src/cmd/go/internal/modget/get.go:1765 +0x597
cmd/go/internal/modget.(*resolver).resolveQueries(0xc0000d8600, {0xb2e7b0, 0xc00002a058}, {0xc0000675f0, 0x2, 0x472485?})
	/usr/local/go/src/cmd/go/internal/modget/get.go:1243 +0x1e5
cmd/go/internal/modget.runGet({0xb2e7b0, 0xc00002a058}, 0xc000028498?, {0xc000024220, 0x2, 0x2})
	/usr/local/go/src/cmd/go/internal/modget/get.go:314 +0x40b
main.invoke(0xe28fa0, {0xc0000241f0, 0x5, 0x5})
	/usr/local/go/src/cmd/go/main.go:225 +0x34e
main.main()
	/usr/local/go/src/cmd/go/main.go:179 +0x7d1
2023/02/09 10:58:38 [FATAL] exit status 2
The command '/bin/sh -c xcaddy build     --with github.com/greenpau/caddy-security     --with github.com/crewjam/saml@v0.4.10=github.com/greenpau/origin_crewjam_saml@v0.4.11-0.20221229165346-936eba92623a     --with github.com/greenpau/caddy-trace     --with github.com/porech/caddy-maxmind-geolocation     --with github.com/caddy-dns/cloudflare     --with github.com/kirsch33/realip' returned a non-zero code: 1
exit status 1
Exit Code 1
```
</details>

**Comment by francislavoie** [comment]
Looks like it failed on github.com/greenpau/caddy-trace. Please try removing that plugin and/or reach out to the plugin author.

**Comment by francislavoie** [comment]
Seems like it's a bug with Go ultimately: https://github.com/golang/go/issues/56494

**Comment by francislavoie** [comment]
I'll close this for now. We're tracking the issue elsewhere.

Sorry for the inconvenience, I don't have a good answer for your right now :grimacing:

**Comment by samcro1967** [comment]
Updated version builds as expected.
