### ISSUE TITLE
Compile error as a plugin with Caddy 2.6.4

### ISSUE THREAD

**Issue by go2tom42** [lucaslorentz/caddy-docker-proxy#469]
Dockerfile
```
ARG CADDY_VERSION=2.6.4
FROM caddy:${CADDY_VERSION}-builder AS builder

RUN xcaddy build \
    --with github.com/greenpau/caddy-security \
    --with github.com/lucaslorentz/caddy-docker-proxy/plugin/v2 

FROM caddy:${CADDY_VERSION}

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

CMD ["caddy", "docker-proxy"]
```

error 
```
28.14 go: added github.com/russellhaering/goxmldsig v1.2.0
#9 28.14 go: added github.com/skip2/go-qrcode v0.0.0-20200617195104-da1b6568686e
#9 28.14 go: upgraded go.uber.org/atomic v1.9.0 => v1.10.0
#9 28.14 go: upgraded go.uber.org/multierr v1.6.0 => v1.9.0
#9 28.15 2023/03/05 07:21:43 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/lucaslorentz/caddy-docker-proxy/plugin/v2 github.com/caddyserver/caddy/v2@v2.6.4 
#9 28.45 go: downloading github.com/lucaslorentz/caddy-docker-proxy v0.3.6
#9 28.52 go: downloading github.com/lucaslorentz/caddy-docker-proxy/plugin/v2 v2.9.9
#9 28.52 go: downloading github.com/lucaslorentz/caddy-docker-proxy/plugin v0.0.0-20220518223657-500809a26c5d
#9 30.10 panic: internal error: can't find reason for requirement on github.com/google/pprof@v0.0.0-20210407192527-94a9f03dee38
#9 30.10 
#9 30.10 goroutine 1 [running]:
#9 30.10 cmd/go/internal/modget.(*resolver).updateBuildList.func1({{0xc00052d548?, 0xc0007c0558?}, {0xc0000b87e0?, 0xc000231ae8?}})
#9 30.10 	/usr/local/go/src/cmd/go/internal/modget/get.go:1760 +0x114
#9 30.10 cmd/go/internal/modget.(*resolver).updateBuildList(0xc0001d0400, {0xb313d0, 0xc00009a000}, {0x0, 0x0, 0x0})
#9 30.10 	/usr/local/go/src/cmd/go/internal/modget/get.go:1765 +0x597
#9 30.10 cmd/go/internal/modget.(*resolver).resolveQueries(0xc0001d0400, {0xb313d0, 0xc00009a000}, {0xc0000935c0, 0x2, 0x472485?})
#9 30.10 	/usr/local/go/src/cmd/go/internal/modget/get.go:1243 +0x1e5
#9 30.10 cmd/go/internal/modget.runGet({0xb313d0, 0xc00009a000}, 0xc0000c4420?, {0xc0000ae160, 0x2, 0x2})
#9 30.10 	/usr/local/go/src/cmd/go/internal/modget/get.go:314 +0x40b
#9 30.10 main.invoke(0xe2cfc0, {0xc0000ae130, 0x5, 0x5})
#9 30.10 	/usr/local/go/src/cmd/go/main.go:225 +0x34e
#9 30.10 main.main()
#9 30.10 	/usr/local/go/src/cmd/go/main.go:179 +0x7d1
#9 30.10 2023/03/05 07:21:45 [FATAL] exit status 2
#9 ERROR: process "/bin/sh -c xcaddy build     --with github.com/greenpau/caddy-security     --with github.com/lucaslorentz/caddy-docker-proxy/plugin/v2" did not complete successfully: exit code: 1
------
 > [builder 2/2] RUN xcaddy build     --with github.com/greenpau/caddy-security     --with github.com/lucaslorentz/caddy-docker-proxy/plugin/v2:
#9 30.10 	/usr/local/go/src/cmd/go/internal/modget/get.go:1765 +0x597
#9 30.10 cmd/go/internal/modget.(*resolver).resolveQueries(0xc0001d0400, {0xb313d0, 0xc00009a000}, {0xc0000935c0, 0x2, 0x472485?})
#9 30.10 	/usr/local/go/src/cmd/go/internal/modget/get.go:1243 +0x1e5
#9 30.10 cmd/go/internal/modget.runGet({0xb313d0, 0xc00009a000}, 0xc0000c4420?, {0xc0000ae160, 0x2, 0x2})
#9 30.10 	/usr/local/go/src/cmd/go/internal/modget/get.go:314 +0x40b
#9 30.10 main.invoke(0xe2cfc0, {0xc0000ae130, 0x5, 0x5})
#9 30.10 	/usr/local/go/src/cmd/go/main.go:225 +0x34e
#9 30.10 main.main()
#9 30.10 	/usr/local/go/src/cmd/go/main.go:179 +0x7d1
#9 30.10 2023/03/05 07:21:45 [FATAL] exit status 2
------
Dockerfile:4
--------------------
   3 |     
   4 | >>> RUN xcaddy build \
   5 | >>>     --with github.com/greenpau/caddy-security \
   6 | >>>     --with github.com/lucaslorentz/caddy-docker-proxy/plugin/v2 
   7 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c xcaddy build     --with github.com/greenpau/caddy-security     --with github.com/lucaslorentz/caddy-docker-proxy/plugin/v2" did not complete successfully: exit code: 1
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c xcaddy build     --with github.com/greenpau/caddy-security     --with github.com/lucaslorentz/caddy-docker-proxy/plugin/v2" did not complete successfully: exit code: 1

```
Using github action (default template) to "compile" https://github.com/go2tom42/caddy-docker-proxy-security/blob/master/.github/workflows/docker-publish.yml

**Comment by francislavoie** [comment]
See the README, remove `/plugin`.

```
github.com/lucaslorentz/caddy-docker-proxy/v2
```
